modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/LunixiaLIVE/chiseledEnchants/issues"

[[mixins]]
    config = "chiseledenchants.common.mixins.json"

[[mods]]
    modId = "chiseledenchants"
    version = "${version}"
    displayName = "chiseledEnchants"
    authors = "LunixiaLIVE"
    credits = "LunixiaLIVE"
    displayURL = "https://github.com/LunixiaLIVE/Lunixia-Minecraft-QOL-Mods"
    logoFile = "assets/chiseledenchants/icon.png"
    description = "Targeted enchanting: stock chiseled bookshelves with single-enchant books to guarantee specific enchantments at the enchanting table."

[[dependencies.chiseledenchants]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.2,26.3)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.chiseledenchants]]
    modId = "minecraft"
    type = "required"
    versionRange = "[26.2,26.3)"
    ordering = "NONE"
    side = "BOTH"

